title: "Jekabs Nelsons | Scientific Consulting"
email: jeekabsnelsons@gmail.com
description: "Numerical modeling, automated data processing pipelines, and scientific fluid dynamics consulting."


linkedin_username: jekabs-nelsons
github_username: jekabs-ledlauzis  # Update this

collections:
  services:
    output: true
    permalink: /services/:path/
  publications:
    output: false # Kept as data files to loop through dynamically
